version: '3.9'

services:
  turtle-app:
    build: .
    container_name: turtle_app
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
